---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: yt-saved-purge
  namespace: default
spec:
  schedule: "* * * * *" # dbg
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: yt-saved-purge
              image: ghcr.io/yt-saved-purge:latest
              env: []
              resources:
                limits:
                  cpu: 500m
                  memory: 500Mi
                requests:
                  cpu: 100m
                  memory: 100Mi
          restartPolicy: OnFailure
